apiVersion: v2
name: resqconnect-app-chart
description: A Helm chart for the ResQConnect disaster relief platform
type: application
version: 1.2.2
dependencies:
  - name: resqconnect-volunteer-service-chart
    alias: volunteer-service
    version: 1.2.2
    repository: file://../../volunteer-service/chart
  - name: resqconnect-request-service-chart
    alias: request-service
    version: 1.2.2
    repository: file://../../request-service/chart
  - name: resqconnect-notification-service-chart
    alias: notification-service
    version: 1.2.2
    repository: file://../../notification-service/chart
  - name: resqconnect-matching-service-chart
    alias: matching-service
    version: 1.2.2
    repository: file://../../matching-service/chart
  - name: resqconnect-coordinator-ui-chart
    alias: coordinator-ui
    version: 1.2.2
    repository: file://../../coordinator-ui/chart
