apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: resqconnect-nlp-service
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: resqconnect
  source:
    repoURL: https://github.com/DKS2301/ResQ-Connect
    targetRevision: gitops
    path: src/nlp-service/chart
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: resqconnect
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true